import {
  Activity,
  AlertTriangle,
  ArrowRight,
  AudioLines,
  BookOpenCheck,
  Bot,
  Boxes,
  Brain,
  Building2,
  CheckCircle2,
  Cloud,
  Cpu,
  Database,
  Eye,
  FileScan,
  FileText,
  Filter,
  FolderTree,
  Gauge,
  GraduationCap,
  Hand,
  Image,
  KeyRound,
  Languages,
  Layers,
  Lightbulb,
  Link2,
  ListChecks,
  Lock,
  Map,
  Megaphone,
  MessageCircleQuestion,
  MessageSquareText,
  Mic,
  Network,
  PenLine,
  Puzzle,
  Quote,
  Rocket,
  Route,
  Scale,
  ScanText,
  Search,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Store,
  Target,
  Timer,
  UserCheck,
  Users,
  Video,
  Volume2,
  Wand2,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const icons = {
  activity: Activity,
  alert: AlertTriangle,
  arrow: ArrowRight,
  audio: AudioLines,
  book: BookOpenCheck,
  bot: Bot,
  boxes: Boxes,
  brain: Brain,
  building: Building2,
  check: CheckCircle2,
  cloud: Cloud,
  cpu: Cpu,
  database: Database,
  eye: Eye,
  filescan: FileScan,
  file: FileText,
  filter: Filter,
  folders: FolderTree,
  gauge: Gauge,
  cap: GraduationCap,
  hand: Hand,
  image: Image,
  key: KeyRound,
  languages: Languages,
  layers: Layers,
  bulb: Lightbulb,
  link: Link2,
  list: ListChecks,
  lock: Lock,
  map: Map,
  megaphone: Megaphone,
  question: MessageCircleQuestion,
  text: MessageSquareText,
  mic: Mic,
  network: Network,
  pen: PenLine,
  puzzle: Puzzle,
  quote: Quote,
  rocket: Rocket,
  route: Route,
  scale: Scale,
  scan: ScanText,
  search: Search,
  shield: ShieldCheck,
  phone: Smartphone,
  sparkles: Sparkles,
  store: Store,
  target: Target,
  timer: Timer,
  usercheck: UserCheck,
  users: Users,
  video: Video,
  volume: Volume2,
  wand: Wand2,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, size = 24, className }: { name: IconName; size?: number; className?: string }) {
  const Cmp = icons[name];
  return <Cmp size={size} strokeWidth={1.8} className={className} aria-hidden />;
}
