/** CompTIA Data Analysis Essentials glossary: [term, definition]. Used by the deck and the flashcards. */
export const daeGlossary: string[][] = [
  ["Absolute reference", "A cell reference locked with $ (e.g. $B$1) so it does not change when a formula is copied."],
  ["Aggregate", "A single value that summarizes many rows, such as a sum, average, count, minimum, or maximum."],
  ["Analysis objective", "The specific business question an analysis must answer, agreed before any data work begins."],
  ["Anonymization", "Removing or masking details that identify individuals so data can be shared safely."],
  ["Append", "Stacking tables with the same columns on top of each other to build one longer table."],
  ["Calculated field", "A new column computed from existing columns, such as Total = Qty × Unit price."],
  ["Cherry-picking", "Showing only the data that supports a conclusion while hiding data that contradicts it."],
  ["Concatenation", "Joining text from two or more cells into one, e.g. with CONCAT, TEXTJOIN, or &."],
  ["Conditional logic", "Formulas that return different results depending on a test, using IF, IFS, AND, and OR."],
  ["CSV", "Comma-separated values: a plain-text file where each line is a row and commas separate the columns."],
  ["Dashboard", "A one-page view that combines KPIs, charts, and filters so stakeholders can monitor results."],
  ["Data dictionary", "Documentation listing each field's name, type, meaning, allowed values, and source."],
  ["Data integrity", "The accuracy, completeness, and consistency of data throughout its life cycle."],
  ["Data type", "The kind of value a column holds, such as text, number, date, currency, or true/false."],
  ["Data validation", "Rules that restrict what can be entered in a cell, such as a dropdown list or a number range."],
  ["Delimiter", "The character that separates values in a text file, such as a comma, tab, or semicolon."],
  ["Descriptive statistics", "Numbers that describe a dataset: mean, median, mode, minimum, maximum, range, and standard deviation."],
  ["Duplicate record", "A row that repeats the same entity more than once, which inflates counts and totals."],
  ["KPI", "Key performance indicator: a measurable value tied to a specific goal, showing progress toward it."],
  ["Lookup", "Retrieving a value from another table by matching a shared key, e.g. with VLOOKUP or XLOOKUP."],
  ["Lookup key", "The column whose values match between two tables, such as Product ID or Employee ID."],
  ["Median", "The middle value when data is sorted; less affected by outliers than the mean."],
  ["Missing value", "A blank or null where data was expected; it must be handled deliberately, not ignored."],
  ["Named range", "A cell or range given a readable name (e.g. TaxRate) that formulas can use instead of an address."],
  ["Normalization (text)", "Making text consistent, e.g. trimming spaces and fixing capitalization so values match."],
  ["Outlier", "A value far from the rest of the data that may be an error or a genuine extreme case."],
  ["PII", "Personally identifiable information: data that can identify a person, such as name, phone, or ID number."],
  ["Pivot table", "An interactive summary that groups and aggregates rows by the fields you drag into it."],
  ["Reproducibility", "Documenting data, steps, and assumptions so someone else can repeat the analysis and get the same result."],
  ["Scope creep", "An analysis gradually expanding beyond the original question, delaying the answer."],
  ["Slicer", "A clickable filter that controls one or more pivot tables or charts at once."],
  ["Stakeholder", "A person who uses the results of an analysis or is affected by the decisions it supports."],
  ["Structured data", "Data organized into rows and columns with consistent fields, ready for analysis."],
  ["Success criteria", "Measurable conditions agreed in advance that show the analysis objective has been met."],
  ["Tidy data", "A layout where each row is one record, each column one variable, and each cell one value."],
  ["Unit of analysis", "The 'thing' each row represents, such as one order, one customer, or one day."],
  ["XLOOKUP", "A lookup function that searches any column and returns a match from any other, with a built-in not-found result."],
];
